# 指定Docker Compose文件格式版本
version: '3.8'

services:
  # RAG智能问答系统服务
  ragchat:
    build: .  # 使用当前目录的Dockerfile构建镜像
    image: r1-rag-project-ragchat:latest  # 指定镜像名称
    container_name: ragchat  # 容器名称
    ports:
      - "8804:8804" # 端口映射,左边是主机端口,右边是容器端口
    volumes:  # 数据卷挂载
      - ./logs:/app/logs  # 挂载日志目录
      - ./vector_db:/app/vector_db  # 挂载向量数据库目录
      - ./.env:/app/.env  # 挂载环境配置文件
      - . :/app
    environment:  # 环境变量设置
      - HOST=0.0.0.0  # 监听所有网络接口
      - PORT=8804  # 应用端口
      - WORKERS=4  # 工作进程数
      - OLLAMA_HOST=http://ollama:11434  # 修改为直接使用服务名
    depends_on:  # 依赖服务
      - ollama  # 依赖于ollama服务
    networks:  # 网络配置
      - ragchat-network  # 使用自定义网络
    extra_hosts:  # 添加主机名解析
      - "host.docker.internal:host-gateway"  # 允许容器访问宿主机服务
    command: ["python", "main.py"] # debug用 注释掉启动命令
    # command: ["/bin/bash"]

  # Ollama大语言模型服务
  ollama:
    image: ollama/ollama:latest  # 使用官方最新镜像
    container_name: ollama  # 容器名称
    volumes:
      - ollama_data:/root/.ollama  # 修改为使用命名卷
    ports:
      - "11434:11434"  # 端口映射
    networks:
      - ragchat-network  # 使用自定义网络
    deploy:
      resources:
        limits:
          memory: 24G  # 内存使用
        reservations:
          devices:
            - driver: nvidia
              count: 1 
              capabilities: [gpu]

# 定义持久化数据卷
volumes:
  ollama_data:  
    name: ollama_data

# 定义自定义网络
networks:
  ragchat-network:  # RAG应用专用网络
    name: ragchat-network  # 网络名称 